### ISSUE TITLE
Will this project return

### ISSUE THREAD

**Issue by CleverSource** [ThalKod/discord-clone#118]
You stopped working on it? Will you work on it again in the future, very promising.

**Comment by ThalKod** [comment]
I have been busy lately..., But Yeah, i'll work on it and add the friends request part.

**Comment by CleverSource** [comment]
You should end up adding user profiles kind of like Discord has for nitro, partners, discord devs, etc.

**Comment by JosGCS** [comment]
@ThalKod You forgot to add CSS Files to your project...

**Comment by ThalKod** [comment]
@JosGCS What CSS Files are you talking about ? The files is there: /public/stylesheets/

**Comment by Puyodead1** [comment]
I will donate to you to keep this alive <3

**Comment by ThalKod** [comment]
@Puyodead1 I will kindly accept ;)

**Comment by whiteyhat** [comment]
> I will donate to you to keep this alive <3

Me too! This project should not die. It is promising. I am happy to contribute
