### ISSUE TITLE
Hello ThalKod

### ISSUE THREAD

**Issue by m1lw0rm** [ThalKod/discord-clone#166]
Hello, The project has potential, I would like to test it mall. But I am still new in the "NodeJs", I have followed your instalation and get this here only

> nodemon app.js

[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
(node:3015) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:3015) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
listenning on 5000

Is that so ok? I can not see the page on my domain?

I'm sorry I'll take your time, and thanks in advance for your help :)

**Comment by unknownguy2002** [comment]
Are you trying it on port 5000?

**Comment by ThalKod** [comment]
Yes, it's normal, it should be running on http://localhost:5000

**Comment by m1lw0rm** [comment]
Oh okay, thanks. Work fine :)
