### ISSUE TITLE
Ban,kick?

### ISSUE THREAD

**Issue by m1lw0rm** [ThalKod/discord-clone#168]
Is there something like "admin panel" for bans, kick etc?

**Comment by ThalKod** [comment]
No there's nothing like that right.., i'm mostly working on other projects, and don't really have time to work on this...

**Comment by para-dise** [comment]
This is **way** more important ofc

**Comment by unknownguy2002** [comment]
I am slowly working on a PR so perhaps I'll add similar functionality. Stay tuned.
